version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgbouncer:
    image: bitnami/pgbouncer:1.21.0
    container_name: ecar_pgbouncer
    restart: always
    ports:
      - "6432:6432"
    environment:
      - POSTGRESQL_HOST=db
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USERNAME=${DB_USER:-ecar_user}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD:-ecar_password}
      - POSTGRESQL_DATABASE=${DB_NAME:-ecar_db}
      - PGBOUNCER_PORT=6432
      - PGBOUNCER_POOL_MODE=transaction
      - PGBOUNCER_MAX_CLIENT_CONN=100
      - PGBOUNCER_DEFAULT_POOL_SIZE=20
      - PGBOUNCER_AUTH_TYPE=md5
      - PGBOUNCER_DATABASE=${DB_NAME:-ecar_db}
      - PGBOUNCER_ADMIN_USERS=postgres,${DB_USER:-ecar_user}
      - PGBOUNCER_IGNORE_STARTUP_PARAMETERS=extra_float_digits
    depends_on:
      - db

  redis:
    image: redis:7.2-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    command: >
      bash -c "/wait &&
               python manage.py migrate &&
               # Run collectstatic now that whitenoise is handling static files
               python manage.py collectstatic --noinput && 
               gunicorn ecar_backend.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    env_file:
      - ./.env
    environment:
      - WAIT_HOSTS=db:5432,redis:6379,pgbouncer:6432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=10
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - REDIS_URL=redis://redis:6379/1
      - DB_HOST=pgbouncer
      - DB_PORT=6432
      - CONN_MAX_AGE=600
      - DJANGO_SETTINGS_MODULE=ecar_backend.settings
    volumes:
      # Only media volume needed by Django itself
      # - static_volume:/app/staticfiles # Not strictly needed by Gunicorn
      - media_volume:/app/media
    ports:
      # Expose port 8000 directly since Nginx is removed
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      pgbouncer:
        condition: service_started
    restart: always

volumes:
  postgres_data:
  redis_data:
  # static_volume: # Not strictly needed if backend doesn't serve static files directly
  media_volume: 