# Generated by Django 5.1.7 on 2025-04-02 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50, verbose_name='Make')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='License Plate')),
                ('vin', models.CharField(blank=True, max_length=17, null=True, verbose_name='VIN')),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='gasoline', max_length=10, verbose_name='Fuel Type')),
                ('mileage', models.PositiveIntegerField(default=0, verbose_name='Mileage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='core.customer')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('service_reminder', 'Service Reminder'), ('service_update', 'Service Update'), ('invoice', 'Invoice'), ('general', 'General')], max_length=20, verbose_name='Type')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.customer')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Service Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=15, verbose_name='Status')),
                ('scheduled_date', models.DateTimeField(verbose_name='Scheduled Date')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Completed Date')),
                ('technician_notes', models.TextField(blank=True, null=True, verbose_name='Technician Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.car')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Invoice Number')),
                ('issued_date', models.DateField(auto_now_add=True, verbose_name='Issued Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='draft', max_length=10, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='PDF File')),
                ('final_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Custom final amount to be displayed to the customer.', max_digits=10, null=True, verbose_name='Final Amount')),
                ('refund_date', models.DateField(blank=True, null=True, verbose_name='Refund Date')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Refund Amount')),
                ('refund_reason', models.TextField(blank=True, null=True, verbose_name='Refund Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='core.service')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('part', 'Part'), ('labor', 'Labor')], max_length=5, verbose_name='Type')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.service')),
            ],
            options={
                'verbose_name': 'Service Item',
                'verbose_name_plural': 'Service Items',
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['user'], name='core_custom_user_id_45895b_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='core_custom_phone_cf7ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['created_at'], name='core_custom_created_629a7b_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['customer'], name='core_car_custome_fa7e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['license_plate'], name='core_car_license_120e5f_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['vin'], name='core_car_vin_60390e_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['make', 'model'], name='core_car_make_deb20a_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['year'], name='core_car_year_8b087a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['customer'], name='core_notifi_custome_d5e864_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='core_notifi_notific_cbfe88_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='core_notifi_is_read_127eae_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='core_notifi_created_d0c445_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['car'], name='core_servic_car_id_912932_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['status'], name='core_servic_status_91b159_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['scheduled_date'], name='core_servic_schedul_4030ba_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['completed_date'], name='core_servic_complet_bbaff5_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['created_at'], name='core_servic_created_6433db_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['service'], name='core_invoic_service_7486b3_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='core_invoic_invoice_aef6bc_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issued_date'], name='core_invoic_issued__0f4a20_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='core_invoic_due_dat_a17de6_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='core_invoic_status_3d8780_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceitem',
            index=models.Index(fields=['service'], name='core_servic_service_4fe05d_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceitem',
            index=models.Index(fields=['item_type'], name='core_servic_item_ty_f7b683_idx'),
        ),
    ]
