# Generated by Django 5.1.7 on 2025-03-31 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['customer'], name='core_car_custome_fa7e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['license_plate'], name='core_car_license_120e5f_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['vin'], name='core_car_vin_60390e_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['make', 'model'], name='core_car_make_deb20a_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['year'], name='core_car_year_8b087a_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['user'], name='core_custom_user_id_45895b_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='core_custom_phone_cf7ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['created_at'], name='core_custom_created_629a7b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['service'], name='core_invoic_service_7486b3_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='core_invoic_invoice_aef6bc_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issued_date'], name='core_invoic_issued__0f4a20_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='core_invoic_due_dat_a17de6_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='core_invoic_status_3d8780_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['customer'], name='core_notifi_custome_d5e864_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='core_notifi_notific_cbfe88_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='core_notifi_is_read_127eae_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='core_notifi_created_d0c445_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['car'], name='core_servic_car_id_912932_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['status'], name='core_servic_status_91b159_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['scheduled_date'], name='core_servic_schedul_4030ba_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['completed_date'], name='core_servic_complet_bbaff5_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['created_at'], name='core_servic_created_6433db_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceitem',
            index=models.Index(fields=['service'], name='core_servic_service_4fe05d_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceitem',
            index=models.Index(fields=['item_type'], name='core_servic_item_ty_f7b683_idx'),
        ),
    ]
