# Generated by Django 5.1.7 on 2025-04-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom final amount to be displayed to the customer.', max_digits=10, null=True, verbose_name='Final Amount'),
        ),
    ] 