# Generated by Django 5.1.7 on 2025-04-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_final_amount_to_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Custom final amount to be displayed to the customer.', max_digits=10, null=True, verbose_name='Final Amount'),
        ),
    ] 