# Generated by Django 5.1.7 on 2025-04-02 21:02

from django.db import migrations, models
import core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_update_final_amount_decimal_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=20, unique=True, validators=[core.models.validate_license_plate], verbose_name='License Plate'),
        ),
    ] 