# Generated by Django 5.1.7 on 2025-04-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_license_plate_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_mileage',
            field=models.PositiveIntegerField(blank=True, help_text="The car's mileage at the time of service", null=True, verbose_name='Service Mileage'),
        ),
    ]
