# Generated by Django 5.1.7 on 2025-04-02 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_car_average_daily_mileage_car_last_service_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_routine_maintenance',
            field=models.BooleanField(default=False, help_text='Whether this service should reset the maintenance interval for prediction purposes.', verbose_name='Routine Maintenance'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(blank=True, help_text='The type of service performed, used for future service predictions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='core.serviceinterval'),
        ),
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(verbose_name='Service Date')),
                ('service_mileage', models.PositiveIntegerField(verbose_name='Service Mileage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_history', to='core.car')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_history_record', to='core.service')),
                ('service_interval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_history', to='core.serviceinterval')),
            ],
            options={
                'verbose_name': 'Service History',
                'verbose_name_plural': 'Service History',
                'ordering': ['-service_date'],
                'indexes': [models.Index(fields=['car'], name='core_servic_car_id_a9253a_idx'), models.Index(fields=['service_date'], name='core_servic_service_04087b_idx'), models.Index(fields=['service_mileage'], name='core_servic_service_c7708f_idx')],
            },
        ),
    ]
