# Generated by Django 5.1.7 on 2025-04-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_service_is_routine_maintenance_service_service_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='initial_mileage',
            field=models.PositiveIntegerField(default=0, help_text='Starting mileage when car was added to the system. Cannot be changed except by superadmin.', verbose_name='Initial Mileage'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(default=0, verbose_name='Current Mileage'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_routine_maintenance',
            field=models.BooleanField(default=False, help_text="Check this box if this service is part of the car's regular maintenance schedule. When checked and the service is completed, a service history record will be created and used for future service predictions. For non-routine repairs (like fixing a broken part), leave this unchecked."),
        ),
    ]
