# Generated by Django 5.1.7 on 2025-04-06 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_car_initial_mileage_alter_car_mileage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(help_text='The user account associated with this customer.', on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Custom final amount to be displayed to the customer.', max_digits=10, null=True, verbose_name='Final Amount'),
        ),
    ]
