# Generated by Django 5.1.7 on 2025-04-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_customer_user_alter_invoice_final_amount'),
    ]

    operations = [
    ]
